"""DanceWibHist generates histograms of Wiberg bond orders"""

import logging
from matplotlib import pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np
from dancelib import dancerunbase


class DanceWibHist(dancerunbase.DanceRunBase):
    """
    DanceWibHist takes Wiberg bond orders from multiple CSV files and generates
    a PDF containing histograms of bond orders in each file and across all
    files.

    Attributes:
        _tri_n_data_csvs: a list of CSV files generated by DanceSaver (or in the
                          same format)
        _output_histogram: the name of the PDF file to which to save the plots
        _histogram_file: the actual file object used to save the plots
        _bond_orders: a list of numpy arrays, where the array at index i holds
                      the bond orders in the file at index i of _tri_n_data_csvs
    """

    #
    # Public
    #

    def __init__(self, tri_n_data_csvs: [str], output_histogram: str):
        super().__init__()
        self._tri_n_data_csvs = tri_n_data_csvs
        self._output_histogram = output_histogram
        self._histogram_file = PdfPages(self._output_histogram)
        self._bond_orders = []

    def run(self):
        """Make all plots"""
        super().check_run_fatal()
        logging.info("STARTING HISTOGRAM PLOTTING")
        self._parse_wiberg()
        self._plot_histograms()
        self._histogram_file.close()
        logging.info(f"Saved plots to {self._output_histogram}")
        logging.info("FINISHED HISTOGRAM PLOTTING")

    #
    # Private
    #

    def _parse_wiberg(self):
        """Parse out wiberg bond orders from all the tri_n_data_csvs"""
        self._bond_orders = []
        for csvfile in self._tri_n_data_csvs:
            self._bond_orders.append(
                np.genfromtxt(
                    csvfile, delimiter=",", skip_header=1, usecols=(0,)))

    def _plot_histograms(self):
        """Plot histograms of the bond orders for each CSV and for all combined"""
        for csvfile, bond_orders in zip(self._tri_n_data_csvs,
                                        self._bond_orders):
            plt.title(csvfile)
            plt.hist(bond_orders)
            self._histogram_file.savefig()

        plt.title("Combined")
        plt.hist(np.concatenate(self._bond_orders))
        self._histogram_file.savefig()
